// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5p9vykMelxDPdIBn9AUv175z-LILAJHs',
    appId: '1:306577115469:web:e5823c442ec43c5c380f04',
    messagingSenderId: '306577115469',
    projectId: 'tracking-driving',
    authDomain: 'tracking-driving.firebaseapp.com',
    storageBucket: 'tracking-driving.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3gqQw888-KFagIR79r7IsRYOtMaLFMX8',
    appId: '1:306577115469:android:7bd2f9f5cb6784d5380f04',
    messagingSenderId: '306577115469',
    projectId: 'tracking-driving',
    storageBucket: 'tracking-driving.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsT9w_5jNzhD9Rz0ANyKm7yFpY2eY_gvw',
    appId: '1:306577115469:ios:7938a16eaab5c36d380f04',
    messagingSenderId: '306577115469',
    projectId: 'tracking-driving',
    storageBucket: 'tracking-driving.appspot.com',
    iosClientId: '306577115469-91ao4b1s8gj52im7bf2t5n7b86ah0v4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackingDriving',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsT9w_5jNzhD9Rz0ANyKm7yFpY2eY_gvw',
    appId: '1:306577115469:ios:2b346aed7cfdd0df380f04',
    messagingSenderId: '306577115469',
    projectId: 'tracking-driving',
    storageBucket: 'tracking-driving.appspot.com',
    iosClientId: '306577115469-dd3laiucumu6rg7ktrfbqjmtva1edlf4.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackingDriving.RunnerTests',
  );
}
