name: viptrack
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2  
  get: ^4.6.5
  flutter_localization: ^0.1.14

  shared_preferences: ^2.2.1  
  flutter_dotenv: ^5.1.0

  flutter_native_splash: ^2.3.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.13.1

  google_sign_in: ^6.1.4
  google_nav_bar: ^5.0.6
  
  google_maps_flutter: ^2.5.0
  shimmer: ^3.0.0
  
  location: ^5.0.0
  geolocator: ^10.1.0

  geocoder2: ^1.4.0
  flutter_polyline_points: ^1.0.0
  mask_text_input_formatter: ^2.5.0
  brasil_fields: ^1.14.0
  uuid: ^4.2.1
  whatsapp_unilink: ^2.1.0
  url_launcher: ^6.1.13
  font_awesome_flutter: ^10.6.0
  
  

  dio: ^5.3.3

  
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.0"

flutter_icons:
  image_path: "assets/images/logo/viptrack_large.png"
  android: true
  ios: true
  adaptive_icon_background: "#000000"
  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/config/
    - assets/images/logo/
 
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf